services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: viralyz
      POSTGRES_PASSWORD: viralyz
      POSTGRES_DB: viralyz
    volumes:
      - viralyz_pg:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: viralyz
      MINIO_ROOT_PASSWORD: viralyzsecret
    volumes:
      - viralyz_minio:/data

  createbuckets:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      mc alias set local http://minio:9000 viralyz viralyzsecret;
      mc mb -p local/viralyz || true;
      mc anonymous set download local/viralyz || true;
      exit 0;
      "

volumes:
  viralyz_pg:
  viralyz_minio:
